name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pre-commit-scans:
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup java
      uses: actions/setup-java@v4
      with:
         distribution: 'temurin' 
         java-version: '21'

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Perform google formatter check
      run: mvn com.spotify.fmt:fmt-maven-plugin:check

    - name: GitLeaks Scan
      uses: zricethezav/gitleaks-action@v1.3.0
      with:
        args: --path=.

    - name: OSS Scan
      run: mvn ossindex:audit
      continue-on-error: true

    - name: OWASP Scan
      run: mvn org.owasp:dependency-check-maven:check

    - name: Build code and create docker images
      run: mvn clean install docker:build
 
